export const edgeLocations: Record<string, string> = {
  // North America - United States
  IAD: 'Ashburn, VA, USA',
  ATL: 'Atlanta, GA, USA',
  BOS: 'Boston, MA, USA',
  ORD: 'Chicago, IL, USA',
  CMH: 'Columbus, OH, USA',
  DFW: 'Dallas, TX, USA',
  DEN: 'Denver, CO, USA',
  HIO: 'Hillsboro, OR, USA',
  IAH: 'Houston, TX, USA',
  JAX: 'Jacksonville, FL, USA',
  MCI: 'Kansas City, MO, USA',
  LAX: 'Los Angeles, CA, USA',
  MIA: 'Miami, FL, USA',
  MSP: 'Minneapolis, MN, USA',
  BNA: 'Nashville, TN, USA',
  JFK: 'New York, NY, USA',
  EWR: 'Newark, NJ, USA',
  PHL: 'Philadelphia, PA, USA',
  PHX: 'Phoenix, AZ, USA',
  PIT: 'Pittsburgh, PA, USA',
  SLC: 'Salt Lake City, UT, USA',
  SFO: 'San Francisco, CA, USA',
  SEA: 'Seattle, WA, USA',
  IND: 'Indianapolis, IN, USA',
  TPA: 'Tampa, FL, USA',

  // North America - Canada
  YYC: 'Calgary, Canada',
  YUL: 'Montreal, Canada',
  YTO: 'Toronto, Canada',
  YVR: 'Vancouver, Canada',

  // South America
  EZE: 'Buenos Aires, Argentina',
  FOR: 'Fortaleza, Brazil',
  GIG: 'Rio de Janeiro, Brazil',
  GRU: 'São Paulo, Brazil',
  SCL: 'Santiago, Chile',
  BOG: 'Bogotá, Colombia',
  LIM: 'Lima, Peru',

  // Europe
  VIE: 'Vienna, Austria',
  BRU: 'Brussels, Belgium',
  SOF: 'Sofia, Bulgaria',
  ZAG: 'Zagreb, Croatia',
  PRG: 'Prague, Czech Republic',
  CPH: 'Copenhagen, Denmark',
  HEL: 'Helsinki, Finland',
  MRS: 'Marseille, France',
  CDG: 'Paris, France',
  TXL: 'Berlin, Germany',
  DUS: 'Düsseldorf, Germany',
  FRA: 'Frankfurt, Germany',
  HAM: 'Hamburg, Germany',
  MUC: 'Munich, Germany',
  ATH: 'Athens, Greece',
  BUD: 'Budapest, Hungary',
  DUB: 'Dublin, Ireland',
  MXP: 'Milan, Italy',
  PMO: 'Palermo, Italy',
  FCO: 'Rome, Italy',
  AMS: 'Amsterdam, Netherlands',
  OSL: 'Oslo, Norway',
  WAW: 'Warsaw, Poland',
  LIS: 'Lisbon, Portugal',
  OTP: 'Bucharest, Romania',
  BCN: 'Barcelona, Spain',
  MAD: 'Madrid, Spain',
  ARN: 'Stockholm, Sweden',
  ZRH: 'Zurich, Switzerland',
  LHR: 'London, UK',
  MAN: 'Manchester, UK',

  // Middle East
  BAH: 'Manama, Bahrain',
  CAI: 'Cairo, Egypt',
  TLV: 'Tel Aviv, Israel',
  MCT: 'Muscat, Oman',
  DOH: 'Doha, Qatar',
  JED: 'Jeddah, Saudi Arabia',
  RUH: 'Riyadh, Saudi Arabia',
  IST: 'Istanbul, Turkey',
  DXB: 'Dubai, UAE',
  FJR: 'Fujairah, UAE',

  // Asia Pacific
  BNE: 'Brisbane, Australia',
  MEL: 'Melbourne, Australia',
  PER: 'Perth, Australia',
  SYD: 'Sydney, Australia',
  HKG: 'Hong Kong',
  TPE: 'Taipei, Taiwan',
  BLR: 'Bangalore, India',
  MAA: 'Chennai, India',
  HYD: 'Hyderabad, India',
  CCU: 'Kolkata, India',
  BOM: 'Mumbai, India',
  DEL: 'New Delhi, India',
  PNQ: 'Pune, India',
  CGK: 'Jakarta, Indonesia',
  KIX: 'Osaka, Japan',
  NRT: 'Tokyo, Japan',
  NBO: 'Nairobi, Kenya',
  KUL: 'Kuala Lumpur, Malaysia',
  QRO: 'Querétaro, Mexico',
  AKL: 'Auckland, New Zealand',
  LOS: 'Lagos, Nigeria',
  MNL: 'Manila, Philippines',
  SIN: 'Singapore',
  CPT: 'Cape Town, South Africa',
  JNB: 'Johannesburg, South Africa',
  ICN: 'Seoul, South Korea',
  BKK: 'Bangkok, Thailand',
  HAN: 'Hanoi, Vietnam',
  SGN: 'Ho Chi Minh City, Vietnam',
};

export function getEdgeLocationName(code: string | null): string | null {
  if (!code) return null;
  
  const prefix = code.substring(0, 3).toUpperCase();
  return edgeLocations[prefix] || code;
}
